apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-ha-config
  namespace: ibm-mq
data:
  mqsc.ini: |
    DEFINE QLOCAL(TEST.QUEUE) REPLACE
    DEFINE QLOCAL(DEV.QUEUE.1) REPLACE
    DEFINE QLOCAL(DEV.QUEUE.2) REPLACE
    DEFINE QLOCAL(DEV.QUEUE.3) REPLACE
    DEFINE CHANNEL(DEV.APP.SVRCONN) CHLTYPE(SVRCONN) REPLACE
    ALTER CHANNEL(DEV.APP.SVRCONN) CHLTYPE(SVRCONN) MCAUSER('app')
    DEFINE CHANNEL(DEV.ADMIN.SVRCONN) CHLTYPE(SVRCONN) REPLACE
    ALTER QMGR CHLAUTH(DISABLED)
    REFRESH SECURITY TYPE(CONNAUTH)
