apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-ha-config
  namespace: ibm-mq
data:
  mqsc.ini: |
    DEFINE QLOCAL(TEST.QUEUE) REPLACE
    DEFINE QLOCAL(SITEB.IN.QUEUE) REPLACE
    DEFINE QLOCAL(SITEB.OUT.QUEUE) REPLACE
    DEFINE CHANNEL(DEV.APP.SVRCONN) CHLTYPE(SVRCONN) REPLACE
    ALTER CHANNEL(DEV.APP.SVRCONN) CHLTYPE(SVRCONN) MCAUSER('app')
    DEFINE CHANNEL(DEV.ADMIN.SVRCONN) CHLTYPE(SVRCONN) REPLACE
    ALTER QMGR CHLAUTH(DISABLED)
    REFRESH SECURITY TYPE(CONNAUTH)
